// beer-data.jsx — Seed beer database (~150 real beers across diverse styles and regions)
// On first run we write to beers:database (shared). On subsequent runs we read, then append
// any seeds missing from the live database (dedup by lower-cased name+brewery).

const STYLES = [
  "IPA", "Double IPA", "Hazy IPA", "American Pale Ale", "Pilsner", "Czech Pilsner",
  "American Lager", "Mexican Lager", "European Lager", "Hefeweizen", "Witbier",
  "Belgian Tripel", "Belgian Dubbel", "Belgian Quadrupel", "Saison", "Brown Ale",
  "Porter", "Imperial Stout", "Irish Stout", "Milk Stout", "Barleywine",
  "Sour Ale", "Gose", "Berliner Weisse", "Lambic", "Wild Ale", "Amber Ale",
  "Red Ale", "Doppelbock", "Bock", "Kölsch", "Cream Ale", "Fruit Beer", "Other"
];

const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
const mk = (name, brewery, style, abv, region) => ({
  id: slug(`${name}-${brewery}`),
  name, brewery, style, abv, region, source: 'seed', added_by_member: null,
});

const BEER_SEEDS = [
  // ── Hop-forward US craft ─────────────────────────────────────
  mk("Pliny the Elder", "Russian River Brewing", "Double IPA", 8.0, "California, USA"),
  mk("Pliny the Younger", "Russian River Brewing", "Triple IPA", 10.25, "California, USA"),
  mk("Heady Topper", "The Alchemist", "Double IPA", 8.0, "Vermont, USA"),
  mk("Focal Banger", "The Alchemist", "IPA", 7.0, "Vermont, USA"),
  mk("Two Hearted Ale", "Bell's Brewery", "IPA", 7.0, "Michigan, USA"),
  mk("Hopslam", "Bell's Brewery", "Double IPA", 10.0, "Michigan, USA"),
  mk("Oberon", "Bell's Brewery", "Wheat Ale", 5.8, "Michigan, USA"),
  mk("Kentucky Breakfast Stout", "Founders Brewing", "Imperial Stout", 12.4, "Michigan, USA"),
  mk("Canadian Breakfast Stout", "Founders Brewing", "Imperial Stout", 11.7, "Michigan, USA"),
  mk("Breakfast Stout", "Founders Brewing", "Imperial Stout", 8.3, "Michigan, USA"),
  mk("All Day IPA", "Founders Brewing", "IPA", 4.7, "Michigan, USA"),
  mk("Solid Gold", "Founders Brewing", "American Lager", 4.4, "Michigan, USA"),
  mk("Sip of Sunshine", "Lawson's Finest Liquids", "IPA", 8.0, "Vermont, USA"),
  mk("Super Session #2", "Lawson's Finest Liquids", "IPA", 4.8, "Vermont, USA"),
  mk("Edward", "Hill Farmstead Brewery", "American Pale Ale", 5.2, "Vermont, USA"),
  mk("Susan", "Hill Farmstead Brewery", "Double IPA", 8.0, "Vermont, USA"),
  mk("Julius", "Tree House Brewing", "Hazy IPA", 6.8, "Massachusetts, USA"),
  mk("Haze", "Tree House Brewing", "Hazy IPA", 7.6, "Massachusetts, USA"),
  mk("Green", "Tree House Brewing", "Hazy IPA", 7.5, "Massachusetts, USA"),
  mk("King Julius", "Tree House Brewing", "Double IPA", 8.3, "Massachusetts, USA"),
  mk("Congress Street IPA", "Trillium Brewing", "IPA", 7.2, "Massachusetts, USA"),
  mk("Fort Point Pale Ale", "Trillium Brewing", "American Pale Ale", 6.6, "Massachusetts, USA"),
  mk("Daydream", "Trillium Brewing", "IPA", 6.5, "Massachusetts, USA"),
  mk("All Citra Everything", "Other Half Brewing", "Double IPA", 8.5, "New York, USA"),
  mk("Forever Ever", "Other Half Brewing", "Hazy IPA", 7.0, "New York, USA"),
  mk("Green Diamonds", "Other Half Brewing", "Double IPA", 8.5, "New York, USA"),
  mk("Foggier Notion", "Monkish Brewing", "Hazy IPA", 7.5, "California, USA"),
  mk("Space Cookie", "Monkish Brewing", "Imperial Stout", 12.0, "California, USA"),
  mk("Torpedo Extra IPA", "Sierra Nevada", "IPA", 7.2, "California, USA"),
  mk("Pale Ale", "Sierra Nevada", "American Pale Ale", 5.6, "California, USA"),
  mk("Hazy Little Thing", "Sierra Nevada", "Hazy IPA", 6.7, "California, USA"),
  mk("Celebration Ale", "Sierra Nevada", "IPA", 6.8, "California, USA"),
  mk("Bigfoot Barleywine", "Sierra Nevada", "Barleywine", 9.6, "California, USA"),
  mk("Stone IPA", "Stone Brewing", "IPA", 6.9, "California, USA"),
  mk("Arrogant Bastard Ale", "Stone Brewing", "American Strong Ale", 7.2, "California, USA"),
  mk("Delicious IPA", "Stone Brewing", "IPA", 7.7, "California, USA"),
  mk("Ruination Double IPA 2.0", "Stone Brewing", "Double IPA", 8.5, "California, USA"),
  mk("60 Minute IPA", "Dogfish Head", "IPA", 6.0, "Delaware, USA"),
  mk("90 Minute IPA", "Dogfish Head", "Double IPA", 9.0, "Delaware, USA"),
  mk("120 Minute IPA", "Dogfish Head", "Triple IPA", 18.0, "Delaware, USA"),
  mk("Punkin Ale", "Dogfish Head", "Pumpkin Ale", 7.0, "Delaware, USA"),
  mk("Mind Haze", "Firestone Walker", "Hazy IPA", 6.2, "California, USA"),
  mk("Union Jack IPA", "Firestone Walker", "IPA", 7.5, "California, USA"),
  mk("Pivo Pils", "Firestone Walker", "Pilsner", 5.3, "California, USA"),
  mk("Parabola", "Firestone Walker", "Imperial Stout", 13.2, "California, USA"),
  mk("805 Blonde Ale", "Firestone Walker", "Blonde Ale", 4.7, "California, USA"),
  mk("Hop Drop 'n Roll", "NoDa Brewing", "IPA", 7.2, "North Carolina, USA"),
  mk("Jai Alai IPA", "Cigar City Brewing", "IPA", 7.5, "Florida, USA"),
  mk("Hunahpu's Imperial Stout", "Cigar City Brewing", "Imperial Stout", 11.0, "Florida, USA"),
  mk("Maduro Brown Ale", "Cigar City Brewing", "Brown Ale", 5.5, "Florida, USA"),
  mk("Lunch", "Maine Beer Company", "IPA", 7.0, "Maine, USA"),
  mk("Dinner", "Maine Beer Company", "Double IPA", 8.2, "Maine, USA"),
  mk("Peeper", "Maine Beer Company", "American Pale Ale", 5.5, "Maine, USA"),
  mk("Yeti Imperial Stout", "Great Divide", "Imperial Stout", 9.5, "Colorado, USA"),
  mk("Bourbon County Brand Stout", "Goose Island", "Imperial Stout", 14.2, "Illinois, USA"),
  mk("Sofie", "Goose Island", "Saison", 6.5, "Illinois, USA"),
  mk("Matilda", "Goose Island", "Belgian Pale Ale", 7.0, "Illinois, USA"),
  mk("312 Urban Wheat Ale", "Goose Island", "Wheat Ale", 4.2, "Illinois, USA"),
  mk("Fundamental Observation", "Bottle Logic Brewing", "Imperial Stout", 14.5, "California, USA"),
  mk("Wee Heavy", "AleSmith Brewing", "Scotch Ale", 10.0, "California, USA"),
  mk("Speedway Stout", "AleSmith Brewing", "Imperial Stout", 12.0, "California, USA"),
  mk(".394 San Diego Pale Ale", "AleSmith Brewing", "American Pale Ale", 6.0, "California, USA"),
  mk("Pseudo Sue", "Toppling Goliath", "American Pale Ale", 5.8, "Iowa, USA"),
  mk("King Sue", "Toppling Goliath", "Double IPA", 7.8, "Iowa, USA"),
  mk("Mornin' Delight", "Toppling Goliath", "Imperial Stout", 12.0, "Iowa, USA"),
  mk("Daisy Cutter", "Half Acre Beer Co.", "American Pale Ale", 5.2, "Illinois, USA"),
  mk("Vienna Lager", "Devils Backbone", "Vienna Lager", 5.2, "Virginia, USA"),
  mk("Sweet Action", "Sixpoint Brewery", "Cream Ale", 5.2, "New York, USA"),
  mk("Resin", "Sixpoint Brewery", "Double IPA", 9.1, "New York, USA"),
  mk("Notch Session Pils", "Notch Brewing", "Pilsner", 4.0, "Massachusetts, USA"),
  mk("Pilz", "Heater Allen", "German Pilsner", 4.9, "Oregon, USA"),
  mk("Pearl Pilsner", "Live Oak Brewing", "Czech Pilsner", 4.6, "Texas, USA"),
  mk("Hefeweizen", "Live Oak Brewing", "Hefeweizen", 5.3, "Texas, USA"),
  mk("Mama's Little Yella Pils", "Oskar Blues", "Pilsner", 5.3, "Colorado, USA"),
  mk("Dale's Pale Ale", "Oskar Blues", "American Pale Ale", 6.5, "Colorado, USA"),
  mk("Old Chub", "Oskar Blues", "Scotch Ale", 8.0, "Colorado, USA"),
  mk("90 Shilling Ale", "Odell Brewing", "Amber Ale", 5.3, "Colorado, USA"),
  mk("IPA", "Odell Brewing", "IPA", 7.0, "Colorado, USA"),
  mk("Crooked Tree IPA", "Dark Horse Brewing", "IPA", 6.5, "Michigan, USA"),

  // ── World classics ──────────────────────────────────────────
  mk("Guinness Draught", "Guinness", "Irish Stout", 4.2, "Dublin, Ireland"),
  mk("Guinness Foreign Extra Stout", "Guinness", "Imperial Stout", 7.5, "Dublin, Ireland"),
  mk("Modelo Especial", "Grupo Modelo", "Mexican Lager", 4.4, "Mexico"),
  mk("Modelo Negra", "Grupo Modelo", "Vienna Lager", 5.4, "Mexico"),
  mk("Corona Extra", "Grupo Modelo", "Mexican Lager", 4.6, "Mexico"),
  mk("Pacifico Clara", "Grupo Modelo", "Mexican Lager", 4.5, "Mexico"),
  mk("Victoria", "Grupo Modelo", "Vienna Lager", 4.0, "Mexico"),
  mk("Tecate", "Heineken Mexico", "Mexican Lager", 4.5, "Mexico"),
  mk("Dos Equis Lager Especial", "Cervecería Cuauhtémoc Moctezuma", "Mexican Lager", 4.2, "Mexico"),
  mk("Heineken Lager", "Heineken", "European Lager", 5.0, "Netherlands"),
  mk("Heineken 0.0", "Heineken", "Non-Alcoholic", 0.0, "Netherlands"),
  mk("Amstel Light", "Heineken", "European Lager", 3.5, "Netherlands"),
  mk("Stella Artois", "Stella Artois", "European Lager", 5.0, "Belgium"),
  mk("Hoegaarden Witbier", "Hoegaarden", "Witbier", 4.9, "Belgium"),
  mk("Pilsner Urquell", "Pilsner Urquell Brewery", "Czech Pilsner", 4.4, "Czech Republic"),
  mk("Budweiser Budvar", "Budweiser Budvar", "Czech Pilsner", 5.0, "Czech Republic"),
  mk("Staropramen", "Staropramen Brewery", "Czech Pilsner", 5.0, "Czech Republic"),
  mk("Hefeweissbier", "Weihenstephaner", "Hefeweizen", 5.4, "Germany"),
  mk("Hefeweissbier Dunkel", "Weihenstephaner", "Hefeweizen", 5.3, "Germany"),
  mk("Vitus", "Weihenstephaner", "Weizenbock", 7.7, "Germany"),
  mk("Hefe-Weißbier Naturtrüb", "Paulaner", "Hefeweizen", 5.5, "Germany"),
  mk("Salvator Doppelbock", "Paulaner", "Doppelbock", 7.9, "Germany"),
  mk("Munich Original Lager", "Hofbräu München", "European Lager", 5.1, "Germany"),
  mk("Augustiner Helles", "Augustiner-Bräu", "Helles Lager", 5.2, "Germany"),
  mk("Spaten Premium Lager", "Spaten-Franziskaner-Bräu", "Helles Lager", 5.2, "Germany"),
  mk("Celebrator Doppelbock", "Ayinger", "Doppelbock", 6.7, "Germany"),
  mk("Schneider Weisse Tap 7", "Schneider Weisse", "Hefeweizen", 5.4, "Germany"),
  mk("Aventinus", "Schneider Weisse", "Weizenbock", 8.2, "Germany"),
  mk("Kölsch", "Reissdorf", "Kölsch", 4.8, "Germany"),
  mk("Bitburger Premium Pilsner", "Bitburger", "German Pilsner", 4.8, "Germany"),
  mk("Beck's", "Brauerei Beck & Co.", "German Pilsner", 5.0, "Germany"),
  mk("Warsteiner Premium Verum", "Warsteiner", "German Pilsner", 4.8, "Germany"),
  mk("Tripel", "Westmalle", "Belgian Tripel", 9.5, "Belgium"),
  mk("Dubbel", "Westmalle", "Belgian Dubbel", 7.0, "Belgium"),
  mk("Grande Réserve (Blue)", "Chimay", "Belgian Strong Dark Ale", 9.0, "Belgium"),
  mk("Première (Red)", "Chimay", "Belgian Dubbel", 7.0, "Belgium"),
  mk("Cinq Cents (White)", "Chimay", "Belgian Tripel", 8.0, "Belgium"),
  mk("Rochefort 10", "Brasserie de Rochefort", "Belgian Quadrupel", 11.3, "Belgium"),
  mk("Rochefort 8", "Brasserie de Rochefort", "Belgian Dubbel", 9.2, "Belgium"),
  mk("Westvleteren 12", "Sint-Sixtusabdij van Westvleteren", "Belgian Quadrupel", 10.2, "Belgium"),
  mk("Orval", "Brasserie d'Orval", "Belgian Pale Ale", 6.2, "Belgium"),
  mk("Duvel", "Duvel Moortgat", "Belgian Strong Pale Ale", 8.5, "Belgium"),
  mk("Delirium Tremens", "Huyghe Brewery", "Belgian Strong Pale Ale", 8.5, "Belgium"),
  mk("Kwak", "Brouwerij Bosteels", "Belgian Strong Pale Ale", 8.4, "Belgium"),
  mk("Tripel Karmeliet", "Brouwerij Bosteels", "Belgian Tripel", 8.4, "Belgium"),
  mk("Saison Dupont", "Brasserie Dupont", "Saison", 6.5, "Belgium"),
  mk("Gueuze", "Brasserie Cantillon", "Lambic", 5.0, "Belgium"),
  mk("Kriek 100% Lambic", "Brasserie Cantillon", "Lambic", 5.0, "Belgium"),
  mk("Rosé de Gambrinus", "Brasserie Cantillon", "Lambic", 5.0, "Belgium"),
  mk("Lindemans Framboise", "Brouwerij Lindemans", "Lambic", 2.5, "Belgium"),
  mk("Timmermans Strawberry Lambicus", "Brouwerij Timmermans", "Lambic", 4.0, "Belgium"),

  // ── UK & Ireland ────────────────────────────────────────────
  mk("London Pride", "Fuller's Brewery", "English Bitter", 4.7, "London, England"),
  mk("ESB", "Fuller's Brewery", "English Bitter", 5.9, "London, England"),
  mk("Vintage Ale", "Fuller's Brewery", "English Strong Ale", 8.5, "London, England"),
  mk("Oatmeal Stout", "Samuel Smith's", "Oatmeal Stout", 5.0, "Yorkshire, England"),
  mk("Nut Brown Ale", "Samuel Smith's", "Brown Ale", 5.0, "Yorkshire, England"),
  mk("Organic Chocolate Stout", "Samuel Smith's", "Milk Stout", 5.0, "Yorkshire, England"),
  mk("Old Speckled Hen", "Morland Brewery", "English Pale Ale", 5.0, "Oxfordshire, England"),
  mk("Newcastle Brown Ale", "Newcastle", "Brown Ale", 4.7, "Newcastle, England"),
  mk("BrewDog Punk IPA", "BrewDog", "IPA", 5.4, "Scotland, UK"),
  mk("BrewDog Elvis Juice", "BrewDog", "IPA", 6.5, "Scotland, UK"),
  mk("Tactical Nuclear Penguin", "BrewDog", "Imperial Stout", 32.0, "Scotland, UK"),
  mk("Murphy's Irish Stout", "Murphy Brewery", "Irish Stout", 4.0, "Cork, Ireland"),
  mk("Smithwick's Irish Red Ale", "Smithwick's", "Irish Red Ale", 4.5, "Kilkenny, Ireland"),
  mk("Magners Original Cider", "Magners", "Cider", 4.5, "Tipperary, Ireland"),

  // ── East Asia & Pacific ─────────────────────────────────────
  mk("Sapporo Premium Beer", "Sapporo Brewery", "Japanese Lager", 4.9, "Japan"),
  mk("Asahi Super Dry", "Asahi Breweries", "Japanese Lager", 5.0, "Japan"),
  mk("Kirin Ichiban", "Kirin Brewery", "Japanese Lager", 5.0, "Japan"),
  mk("Yebisu", "Sapporo Brewery", "Japanese Lager", 5.0, "Japan"),
  mk("Nest White Ale", "Hitachino Nest", "Witbier", 5.5, "Japan"),
  mk("Nest XH Ale", "Hitachino Nest", "Belgian Strong Dark Ale", 7.0, "Japan"),
  mk("Tsingtao", "Tsingtao Brewery", "Asian Lager", 4.7, "China"),
  mk("Hite", "Hite Brewery", "Asian Lager", 4.5, "South Korea"),
  mk("Singha", "Boon Rawd Brewery", "Asian Lager", 5.0, "Thailand"),
  mk("Chang", "Thai Beverage", "Asian Lager", 5.0, "Thailand"),
  mk("Tiger Beer", "Asia Pacific Breweries", "Asian Lager", 5.0, "Singapore"),
  mk("Saigon Special", "SABECO", "Asian Lager", 4.9, "Vietnam"),
  mk("Stone & Wood Pacific Ale", "Stone & Wood Brewing", "Pacific Ale", 4.4, "Australia"),
  mk("Coopers Sparkling Ale", "Coopers Brewery", "Australian Pale Ale", 5.8, "Australia"),
  mk("Little Creatures Pale Ale", "Little Creatures Brewing", "American Pale Ale", 5.2, "Australia"),
  mk("VB Victoria Bitter", "Carlton & United Breweries", "Australian Lager", 4.6, "Australia"),
  mk("Garage Project Hāpi Daze", "Garage Project", "American Pale Ale", 4.6, "New Zealand"),
  mk("Garage Project Pernicious Weed", "Garage Project", "Double IPA", 8.0, "New Zealand"),
  mk("Panhead Supercharger APA", "Panhead Custom Ales", "American Pale Ale", 5.7, "New Zealand"),
  mk("Tui East India Pale Ale", "DB Breweries", "Pale Ale", 4.0, "New Zealand"),

  // ── Latin America & Iberian ─────────────────────────────────
  mk("Estrella Damm", "Estrella Damm", "European Lager", 4.6, "Barcelona, Spain"),
  mk("Inedit", "Estrella Damm", "Witbier", 4.8, "Barcelona, Spain"),
  mk("Mahou Cinco Estrellas", "Mahou", "European Lager", 5.5, "Madrid, Spain"),
  mk("Alhambra Reserva 1925", "Cervezas Alhambra", "European Lager", 6.4, "Granada, Spain"),
  mk("Sagres", "SCC Sagres", "European Lager", 5.0, "Portugal"),
  mk("Super Bock", "Unicer", "European Lager", 5.2, "Portugal"),
  mk("Patagonia Amber Lager", "Cerveza Patagonia", "Vienna Lager", 4.5, "Argentina"),
  mk("Brahma Chopp", "Ambev", "American Lager", 4.3, "Brazil"),
  mk("Antarctica Original", "Ambev", "American Lager", 5.0, "Brazil"),
  mk("Polar Pilsen", "Cervecería Polar", "European Lager", 5.2, "Venezuela"),
  mk("Cusqueña", "Backus & Johnston", "European Lager", 5.0, "Peru"),

  // ── Italian craft & European craft ──────────────────────────
  mk("Tipopils", "Birrificio Italiano", "German Pilsner", 5.2, "Italy"),
  mk("Re Ale", "Birra del Borgo", "American Pale Ale", 6.4, "Italy"),
  mk("Nazionale", "Birra del Borgo", "Saison", 6.4, "Italy"),
  mk("Ghisa Smoked Stout", "Lambrate", "Smoked Stout", 5.0, "Italy"),
  mk("Carlsberg Pilsner", "Carlsberg", "European Lager", 5.0, "Copenhagen, Denmark"),
  mk("Mikkeller Beer Geek Breakfast", "Mikkeller", "Imperial Stout", 7.5, "Copenhagen, Denmark"),
  mk("To Øl Sur Mexicane", "To Øl", "Sour Ale", 4.5, "Copenhagen, Denmark"),

  // ── Sours, wild, funk (US) ──────────────────────────────────
  mk("Supplication", "Russian River Brewing", "Wild Ale", 7.0, "California, USA"),
  mk("Sanctification", "Russian River Brewing", "Wild Ale", 6.75, "California, USA"),
  mk("Damnation", "Russian River Brewing", "Belgian Strong Pale Ale", 7.75, "California, USA"),
  mk("Le Petit Prince", "Jester King Brewery", "Farmhouse Ale", 2.9, "Texas, USA"),
  mk("Atrial Rubicite", "Jester King Brewery", "Wild Ale", 5.8, "Texas, USA"),
  mk("Boulevard Tank 7", "Boulevard Brewing", "Saison", 8.5, "Missouri, USA"),
  mk("La Folie", "New Belgium Brewing", "Wild Ale", 7.0, "Colorado, USA"),
  mk("Fat Tire Amber Ale", "New Belgium Brewing", "Amber Ale", 5.2, "Colorado, USA"),
  mk("Voodoo Ranger IPA", "New Belgium Brewing", "IPA", 7.0, "Colorado, USA"),
  mk("Voodoo Ranger Imperial IPA", "New Belgium Brewing", "Double IPA", 9.0, "Colorado, USA"),

  // ── Big domestic American lagers (gotta have them) ─────────
  mk("Budweiser", "Anheuser-Busch", "American Lager", 5.0, "Missouri, USA"),
  mk("Bud Light", "Anheuser-Busch", "American Light Lager", 4.2, "Missouri, USA"),
  mk("Miller Lite", "Molson Coors", "American Light Lager", 4.2, "Illinois, USA"),
  mk("Miller High Life", "Molson Coors", "American Lager", 4.6, "Wisconsin, USA"),
  mk("Coors Banquet", "Molson Coors", "American Lager", 5.0, "Colorado, USA"),
  mk("Coors Light", "Molson Coors", "American Light Lager", 4.2, "Colorado, USA"),
  mk("Pabst Blue Ribbon", "Pabst Brewing Co.", "American Lager", 4.74, "California, USA"),
  mk("Yuengling Traditional Lager", "D.G. Yuengling & Son", "Amber Lager", 4.5, "Pennsylvania, USA"),
  mk("Narragansett Lager", "Narragansett Brewing", "American Lager", 5.0, "Rhode Island, USA"),
  mk("Genesee Cream Ale", "Genesee Brewing", "Cream Ale", 5.1, "New York, USA"),
  mk("Lone Star", "Pabst Brewing Co.", "American Lager", 4.7, "Texas, USA"),
  mk("Shiner Bock", "Spoetzl Brewery", "Bock", 4.4, "Texas, USA"),
  mk("Samuel Adams Boston Lager", "Boston Beer Company", "Vienna Lager", 5.0, "Massachusetts, USA"),
  mk("Sam Adams Cherry Wheat", "Boston Beer Company", "Fruit Beer", 5.4, "Massachusetts, USA"),
  mk("Allagash White", "Allagash Brewing", "Witbier", 5.2, "Maine, USA"),
  mk("Allagash Curieux", "Allagash Brewing", "Belgian Tripel", 11.0, "Maine, USA"),
  mk("Anchor Steam Beer", "Anchor Brewing", "California Common", 4.9, "California, USA"),
  mk("Anchor Porter", "Anchor Brewing", "Porter", 5.6, "California, USA"),
  mk("Brooklyn Lager", "Brooklyn Brewery", "Vienna Lager", 5.2, "New York, USA"),
  mk("Brooklyn Black Chocolate Stout", "Brooklyn Brewery", "Imperial Stout", 10.0, "New York, USA"),
  mk("Sour Monkey", "Victory Brewing", "Sour Ale", 9.5, "Pennsylvania, USA"),
  mk("Hop Devil", "Victory Brewing", "IPA", 6.7, "Pennsylvania, USA"),
  mk("Prima Pils", "Victory Brewing", "German Pilsner", 5.3, "Pennsylvania, USA"),

  // ── Expanded library: more US craft ─────────────────────────
  mk("Zombie Dust", "3 Floyds Brewing", "American Pale Ale", 6.4, "Indiana, USA"),
  mk("Dark Lord", "3 Floyds Brewing", "Imperial Stout", 15.0, "Indiana, USA"),
  mk("Gumballhead", "3 Floyds Brewing", "American Pale Wheat Ale", 5.6, "Indiana, USA"),
  mk("Alpha King", "3 Floyds Brewing", "American Pale Ale", 6.66, "Indiana, USA"),
  mk("Ten Fidy", "Oskar Blues", "Imperial Stout", 10.5, "Colorado, USA"),
  mk("Pinner Throwback IPA", "Oskar Blues", "Session IPA", 4.9, "Colorado, USA"),
  mk("Modus Hoperandi", "Ska Brewing", "IPA", 6.8, "Colorado, USA"),
  mk("Easy Street Wheat", "Odell Brewing", "American Pale Wheat Ale", 4.6, "Colorado, USA"),
  mk("Cutthroat Porter", "Odell Brewing", "Porter", 5.1, "Colorado, USA"),
  mk("Avery IPA", "Avery Brewing", "IPA", 6.5, "Colorado, USA"),
  mk("Avery The Reverend", "Avery Brewing", "Belgian Quadrupel", 10.0, "Colorado, USA"),
  mk("Dales Cone Crusher", "Oskar Blues", "Double IPA", 8.7, "Colorado, USA"),
  mk("Snake Dog IPA", "Flying Dog", "IPA", 7.1, "Maryland, USA"),
  mk("Raging Bitch", "Flying Dog", "Belgian IPA", 8.3, "Maryland, USA"),
  mk("Old Stock Ale", "North Coast Brewing", "Old Ale", 12.5, "California, USA"),
  mk("Pranqster", "North Coast Brewing", "Belgian Strong Pale Ale", 7.6, "California, USA"),
  mk("Old Rasputin", "North Coast Brewing", "Imperial Stout", 9.0, "California, USA"),
  mk("Racer 5", "Bear Republic", "IPA", 7.5, "California, USA"),
  mk("Hop Rod Rye", "Bear Republic", "Rye IPA", 8.0, "California, USA"),
  mk("Lagunitas IPA", "Lagunitas Brewing", "IPA", 6.2, "California, USA"),
  mk("Sucks", "Lagunitas Brewing", "Double IPA", 7.85, "California, USA"),
  mk("Maximus", "Lagunitas Brewing", "Double IPA", 8.2, "California, USA"),
  mk("Little Sumpin' Sumpin'", "Lagunitas Brewing", "American Pale Wheat Ale", 7.5, "California, USA"),
  mk("Cappuccino Stout", "Lagunitas Brewing", "Imperial Stout", 9.2, "California, USA"),
  mk("Sublimely Self-Righteous", "Stone Brewing", "Black IPA", 8.7, "California, USA"),
  mk("Stone Ruination", "Stone Brewing", "Double IPA", 8.5, "California, USA"),
  mk("Stone Tropic of Thunder", "Stone Brewing", "Tropical Lager", 5.8, "California, USA"),
  mk("Karl Strauss Mosaic Session IPA", "Karl Strauss", "Session IPA", 5.5, "California, USA"),
  mk("Ballast Point Sculpin", "Ballast Point", "IPA", 7.0, "California, USA"),
  mk("Ballast Point Grapefruit Sculpin", "Ballast Point", "IPA", 7.0, "California, USA"),
  mk("Ballast Point Victory at Sea", "Ballast Point", "Imperial Porter", 10.0, "California, USA"),
  mk("Green Flash West Coast IPA", "Green Flash Brewing", "IPA", 8.1, "California, USA"),
  mk("Coronado Mermaid's Red", "Coronado Brewing", "Red Ale", 7.0, "California, USA"),
  mk("Modern Times Orderville", "Modern Times Beer", "Hazy IPA", 7.2, "California, USA"),
  mk("Modern Times Black House", "Modern Times Beer", "Oatmeal Coffee Stout", 5.8, "California, USA"),
  mk("North Park Hop-Fu", "North Park Beer Co.", "IPA", 7.2, "California, USA"),
  mk("Societe The Pupil", "Societe Brewing", "IPA", 7.5, "California, USA"),
  mk("Boochcraft Grapefruit Hibiscus", "Boochcraft", "Hard Kombucha", 7.0, "California, USA"),
  mk("Speakeasy Big Daddy IPA", "Speakeasy Ales", "IPA", 6.5, "California, USA"),
  mk("21st Amendment Brew Free or Die IPA", "21st Amendment", "IPA", 7.0, "California, USA"),
  mk("21st Amendment Hell or High Watermelon", "21st Amendment", "Fruit Beer", 4.9, "California, USA"),
  mk("Drake's 1500", "Drake's Brewing", "American Pale Ale", 5.5, "California, USA"),
  mk("Pizza Port Swami's IPA", "Pizza Port Brewing", "IPA", 6.8, "California, USA"),
  mk("Port Brewing Mongo", "Port Brewing", "Double IPA", 8.5, "California, USA"),
  mk("The Lost Abbey Judgment Day", "The Lost Abbey", "Belgian Quadrupel", 10.5, "California, USA"),
  mk("The Bruery Black Tuesday", "The Bruery", "Imperial Stout", 19.5, "California, USA"),
  mk("The Bruery Or Xata", "The Bruery", "Witbier", 5.7, "California, USA"),
  mk("Almanac Sournova", "Almanac Beer Co.", "Sour Ale", 5.5, "California, USA"),
  mk("Faction Pale Ale", "Faction Brewing", "American Pale Ale", 5.4, "California, USA"),
  mk("Cellarmaker Dobis", "Cellarmaker Brewing", "Hazy IPA", 8.0, "California, USA"),
  mk("Cellarmaker Coffee & Cigarettes", "Cellarmaker Brewing", "Coffee Porter", 6.0, "California, USA"),
  mk("Henhouse Saison", "Henhouse Brewing", "Saison", 5.5, "California, USA"),
  mk("Russian River Blind Pig", "Russian River Brewing", "IPA", 6.1, "California, USA"),
  mk("Russian River STS Pils", "Russian River Brewing", "German Pilsner", 5.5, "California, USA"),
  mk("Russian River Consecration", "Russian River Brewing", "Wild Ale", 10.0, "California, USA"),
  mk("Russian River Temptation", "Russian River Brewing", "Wild Ale", 7.5, "California, USA"),

  // ── More East Coast / NE craft ──────────────────────────────
  mk("Tree House Sap", "Tree House Brewing", "American Pale Ale", 5.5, "Massachusetts, USA"),
  mk("Tree House Bright", "Tree House Brewing", "IPA", 6.4, "Massachusetts, USA"),
  mk("Tree House Doppelganger", "Tree House Brewing", "Double IPA", 8.6, "Massachusetts, USA"),
  mk("Tree House Lights On", "Tree House Brewing", "Hazy IPA", 6.3, "Massachusetts, USA"),
  mk("Trillium Headroom", "Trillium Brewing", "Double IPA", 8.0, "Massachusetts, USA"),
  mk("Trillium Dialed In", "Trillium Brewing", "Hazy IPA", 7.0, "Massachusetts, USA"),
  mk("Trillium Melcher Street", "Trillium Brewing", "Double IPA", 8.0, "Massachusetts, USA"),
  mk("Night Shift Whirlpool", "Night Shift Brewing", "American Pale Ale", 4.5, "Massachusetts, USA"),
  mk("Night Shift Santilli", "Night Shift Brewing", "IPA", 6.0, "Massachusetts, USA"),
  mk("Jack's Abby House Lager", "Jack's Abby", "Helles Lager", 5.2, "Massachusetts, USA"),
  mk("Jack's Abby Hoponius Union", "Jack's Abby", "India Pale Lager", 6.5, "Massachusetts, USA"),
  mk("Notch Czech-Style Pils", "Notch Brewing", "Czech Pilsner", 4.4, "Massachusetts, USA"),
  mk("Mast Landing Tell Tale", "Mast Landing Brewing", "American Pale Ale", 5.4, "Maine, USA"),
  mk("Bissell Brothers Substance", "Bissell Brothers", "American Pale Ale", 6.6, "Maine, USA"),
  mk("Bissell Brothers Reciprocal", "Bissell Brothers", "Double IPA", 8.2, "Maine, USA"),
  mk("Foundation Epiphany", "Foundation Brewing", "Double IPA", 8.4, "Maine, USA"),
  mk("Other Half Mylar Bags", "Other Half Brewing", "Double IPA", 8.5, "New York, USA"),
  mk("Other Half Big Green", "Other Half Brewing", "Triple IPA", 10.5, "New York, USA"),
  mk("Other Half DDH Citra Daydream", "Other Half Brewing", "IPA", 7.0, "New York, USA"),
  mk("Grimm Tesseract", "Grimm Artisanal Ales", "Double IPA", 8.0, "New York, USA"),
  mk("Grimm Lumen", "Grimm Artisanal Ales", "Pilsner", 5.0, "New York, USA"),
  mk("Threes Logical Conclusion", "Threes Brewing", "Pilsner", 4.8, "New York, USA"),
  mk("Threes Vliet", "Threes Brewing", "Pilsner", 4.8, "New York, USA"),
  mk("Brooklyn East IPA", "Brooklyn Brewery", "IPA", 6.9, "New York, USA"),
  mk("Brooklyn Pulp Art", "Brooklyn Brewery", "Hazy IPA", 6.8, "New York, USA"),
  mk("KCBC Cosmic Beverage", "Kings County Brewers Collective", "IPA", 6.2, "New York, USA"),
  mk("SingleCut 18-Watt Session IPA", "SingleCut Beersmiths", "Session IPA", 4.5, "New York, USA"),
  mk("Tröegs Perpetual IPA", "Tröegs", "IPA", 7.5, "Pennsylvania, USA"),
  mk("Tröegs Mad Elf", "Tröegs", "Belgian Strong Dark Ale", 11.0, "Pennsylvania, USA"),
  mk("Yards Brawler", "Yards Brewing", "English Mild", 4.2, "Pennsylvania, USA"),
  mk("Yards Philadelphia Pale Ale", "Yards Brewing", "American Pale Ale", 4.6, "Pennsylvania, USA"),
  mk("Evil Genius Stacy's Mom", "Evil Genius Beer", "Mango IPA", 7.2, "Pennsylvania, USA"),

  // ── Mid-Atlantic / South ────────────────────────────────────
  mk("Wicked Weed Pernicious IPA", "Wicked Weed Brewing", "IPA", 7.3, "North Carolina, USA"),
  mk("Wicked Weed Freak of Nature", "Wicked Weed Brewing", "Double IPA", 8.5, "North Carolina, USA"),
  mk("Highland Gaelic Ale", "Highland Brewing", "Amber Ale", 5.8, "North Carolina, USA"),
  mk("Highland Mocha Stout", "Highland Brewing", "Stout", 5.6, "North Carolina, USA"),
  mk("Burial Skillet Donut Stout", "Burial Beer", "Imperial Stout", 9.0, "North Carolina, USA"),
  mk("Hi-Wire Bed of Nails Brown", "Hi-Wire Brewing", "Brown Ale", 5.8, "North Carolina, USA"),
  mk("Olde Mecklenburg Captain Jack Pilsner", "Olde Mecklenburg", "Pilsner", 5.1, "North Carolina, USA"),
  mk("Westbrook Mexican Cake", "Westbrook Brewing", "Imperial Stout", 10.5, "South Carolina, USA"),
  mk("Westbrook White Thai", "Westbrook Brewing", "Witbier", 5.0, "South Carolina, USA"),
  mk("Sweetwater 420 Extra Pale Ale", "SweetWater Brewing", "American Pale Ale", 5.7, "Georgia, USA"),
  mk("Sweetwater IPA", "SweetWater Brewing", "IPA", 6.3, "Georgia, USA"),
  mk("Creature Comforts Tropicalia", "Creature Comforts", "IPA", 6.6, "Georgia, USA"),
  mk("Creature Comforts Athena", "Creature Comforts", "Berliner Weisse", 4.5, "Georgia, USA"),
  mk("Terrapin Hopsecutioner", "Terrapin Beer Co.", "IPA", 7.3, "Georgia, USA"),
  mk("Yazoo Sue", "Yazoo Brewing", "Smoked Porter", 9.2, "Tennessee, USA"),
  mk("Wiseacre Tiny Bomb", "Wiseacre Brewing", "Pilsner", 4.5, "Tennessee, USA"),
  mk("Founders Porter", "Founders Brewing", "Porter", 6.5, "Michigan, USA"),
  mk("Founders Dirty Bastard", "Founders Brewing", "Scotch Ale", 8.5, "Michigan, USA"),
  mk("Founders Centennial IPA", "Founders Brewing", "IPA", 7.2, "Michigan, USA"),
  mk("Short's Huma-Lupa-Licious", "Short's Brewing", "IPA", 7.7, "Michigan, USA"),
  mk("New Holland Dragon's Milk", "New Holland Brewing", "Imperial Stout", 11.0, "Michigan, USA"),
  mk("Atwater Vanilla Java Porter", "Atwater Brewery", "Porter", 6.0, "Michigan, USA"),
  mk("Founders Backwoods Bastard", "Founders Brewing", "Scotch Ale", 11.6, "Michigan, USA"),
  mk("Goose Island Lolita", "Goose Island", "Wild Ale", 7.0, "Illinois, USA"),
  mk("Half Acre Lager Town", "Half Acre Beer Co.", "American Lager", 5.0, "Illinois, USA"),
  mk("Half Acre Pony", "Half Acre Beer Co.", "American Pale Ale", 5.8, "Illinois, USA"),
  mk("Revolution Anti-Hero IPA", "Revolution Brewing", "IPA", 6.7, "Illinois, USA"),
  mk("Revolution Deth's Tar", "Revolution Brewing", "Imperial Stout", 14.8, "Illinois, USA"),
  mk("Off Color Apex Predator", "Off Color Brewing", "Farmhouse Ale", 6.5, "Illinois, USA"),
  mk("Pipeworks Ninja vs. Unicorn", "Pipeworks Brewing", "Double IPA", 8.0, "Illinois, USA"),
  mk("New Glarus Spotted Cow", "New Glarus Brewing", "Cream Ale", 4.8, "Wisconsin, USA"),
  mk("New Glarus Moon Man", "New Glarus Brewing", "American Pale Ale", 5.0, "Wisconsin, USA"),
  mk("Lakefront Riverwest Stein", "Lakefront Brewery", "Amber Lager", 5.7, "Wisconsin, USA"),
  mk("Surly Furious", "Surly Brewing", "IPA", 6.7, "Minnesota, USA"),
  mk("Surly Darkness", "Surly Brewing", "Imperial Stout", 12.0, "Minnesota, USA"),
  mk("Indeed Day Tripper", "Indeed Brewing", "American Pale Ale", 5.4, "Minnesota, USA"),
  mk("Schell's Firebrick", "August Schell Brewing", "Vienna Lager", 5.0, "Minnesota, USA"),
  mk("Summit EPA", "Summit Brewing", "American Pale Ale", 5.3, "Minnesota, USA"),
  mk("Boulevard Unfiltered Wheat", "Boulevard Brewing", "American Wheat Ale", 4.4, "Missouri, USA"),
  mk("Boulevard Single-Wide IPA", "Boulevard Brewing", "IPA", 5.7, "Missouri, USA"),
  mk("Schlafly Pale Ale", "Schlafly Beer", "English Pale Ale", 4.4, "Missouri, USA"),
  mk("Toppling Goliath Dorothy's New World Lager", "Toppling Goliath", "Helles Lager", 5.5, "Iowa, USA"),
  mk("Toppling Goliath PseudoSue Lager", "Toppling Goliath", "American Lager", 5.0, "Iowa, USA"),
  mk("Toppling Goliath Assassin", "Toppling Goliath", "Imperial Stout", 12.5, "Iowa, USA"),
  mk("Exile Ruthie", "Exile Brewing", "Helles Lager", 5.6, "Iowa, USA"),
  mk("Big Grove Easy Eddy", "Big Grove Brewery", "Session IPA", 4.5, "Iowa, USA"),

  // ── Texas + Mountain ────────────────────────────────────────
  mk("Real Ale Fireman's #4", "Real Ale Brewing", "Blonde Ale", 5.0, "Texas, USA"),
  mk("Real Ale Devil's Backbone", "Real Ale Brewing", "Belgian Tripel", 8.0, "Texas, USA"),
  mk("Karbach Hopadillo", "Karbach Brewing", "IPA", 6.6, "Texas, USA"),
  mk("Karbach Love Street", "Karbach Brewing", "Kölsch", 4.9, "Texas, USA"),
  mk("Saint Arnold Lawnmower", "Saint Arnold Brewing", "Kölsch", 4.9, "Texas, USA"),
  mk("Saint Arnold Art Car IPA", "Saint Arnold Brewing", "IPA", 6.0, "Texas, USA"),
  mk("Community Mosaic IPA", "Community Beer Co.", "IPA", 8.4, "Texas, USA"),
  mk("(512) Pecan Porter", "(512) Brewing", "Porter", 6.8, "Texas, USA"),
  mk("Austin Beerworks Pearl Snap", "Austin Beerworks", "German Pilsner", 5.3, "Texas, USA"),
  mk("Hops & Grain ALT-eration", "Hops & Grain", "Altbier", 6.0, "Texas, USA"),
  mk("Crooked Stave St. Bretta", "Crooked Stave", "Wild Ale", 5.5, "Colorado, USA"),
  mk("Crooked Stave Surette", "Crooked Stave", "Saison", 6.2, "Colorado, USA"),
  mk("Great Divide Hercules", "Great Divide Brewing", "Double IPA", 10.0, "Colorado, USA"),
  mk("Great Divide Titan IPA", "Great Divide Brewing", "IPA", 7.1, "Colorado, USA"),
  mk("Wynkoop Rocky Mountain Oyster Stout", "Wynkoop Brewing", "Stout", 7.0, "Colorado, USA"),
  mk("Telluride Face Down Brown", "Telluride Brewing", "Brown Ale", 5.7, "Colorado, USA"),
  mk("Upslope Craft Lager", "Upslope Brewing", "American Lager", 4.8, "Colorado, USA"),
  mk("Epic Big Bad Baptist", "Epic Brewing", "Imperial Stout", 11.8, "Utah, USA"),
  mk("Uinta Hop Nosh", "Uinta Brewing", "IPA", 7.3, "Utah, USA"),
  mk("Squatters Hop Rising", "Squatters Brewing", "Double IPA", 9.0, "Utah, USA"),
  mk("Kona Big Wave", "Kona Brewing", "Golden Ale", 4.4, "Hawaii, USA"),
  mk("Kona Longboard Island Lager", "Kona Brewing", "Pale Lager", 4.6, "Hawaii, USA"),
  mk("Maui Bikini Blonde", "Maui Brewing", "Helles Lager", 5.1, "Hawaii, USA"),
  mk("Maui Coconut Hiwa Porter", "Maui Brewing", "Porter", 6.0, "Hawaii, USA"),

  // ── Pacific Northwest ───────────────────────────────────────
  mk("Deschutes Black Butte Porter", "Deschutes Brewery", "Porter", 5.5, "Oregon, USA"),
  mk("Deschutes Mirror Pond Pale Ale", "Deschutes Brewery", "American Pale Ale", 5.0, "Oregon, USA"),
  mk("Deschutes Fresh Squeezed IPA", "Deschutes Brewery", "IPA", 6.4, "Oregon, USA"),
  mk("Deschutes The Abyss", "Deschutes Brewery", "Imperial Stout", 11.4, "Oregon, USA"),
  mk("Rogue Dead Guy Ale", "Rogue Ales", "German Maibock", 6.8, "Oregon, USA"),
  mk("Rogue Hazelnut Brown Nectar", "Rogue Ales", "Brown Ale", 6.0, "Oregon, USA"),
  mk("Ninkasi Total Domination", "Ninkasi Brewing", "IPA", 6.7, "Oregon, USA"),
  mk("Ninkasi Tricerahops", "Ninkasi Brewing", "Double IPA", 8.0, "Oregon, USA"),
  mk("Pelican Kiwanda Cream Ale", "Pelican Brewing", "Cream Ale", 5.4, "Oregon, USA"),
  mk("Boneyard RPM IPA", "Boneyard Beer", "IPA", 6.5, "Oregon, USA"),
  mk("Breakside IPA", "Breakside Brewery", "IPA", 6.2, "Oregon, USA"),
  mk("pFriem Pilsner", "pFriem Family Brewers", "Pilsner", 4.9, "Oregon, USA"),
  mk("pFriem IPA", "pFriem Family Brewers", "IPA", 7.2, "Oregon, USA"),
  mk("Cascade Lakes 20\" Brown", "Cascade Lakes", "Brown Ale", 5.5, "Oregon, USA"),
  mk("Block 15 Sticky Hands", "Block 15 Brewing", "Hazy IPA", 8.1, "Oregon, USA"),
  mk("Fort George 3-Way IPA", "Fort George Brewery", "IPA", 7.5, "Oregon, USA"),
  mk("Buoy Czech Pils", "Buoy Beer", "Czech Pilsner", 5.0, "Oregon, USA"),
  mk("Reuben's Brews Crikey IPA", "Reuben's Brews", "IPA", 6.7, "Washington, USA"),
  mk("Reuben's Brews Hazealicious", "Reuben's Brews", "Hazy IPA", 6.5, "Washington, USA"),
  mk("Fremont Lush IPA", "Fremont Brewing", "IPA", 7.0, "Washington, USA"),
  mk("Fremont Dark Star", "Fremont Brewing", "Imperial Stout", 8.5, "Washington, USA"),
  mk("Georgetown Bodhizafa", "Georgetown Brewing", "IPA", 6.9, "Washington, USA"),
  mk("Georgetown Manny's Pale Ale", "Georgetown Brewing", "American Pale Ale", 5.4, "Washington, USA"),
  mk("Elysian Space Dust IPA", "Elysian Brewing", "IPA", 8.2, "Washington, USA"),
  mk("Elysian Superfuzz Blood Orange Pale", "Elysian Brewing", "American Pale Ale", 5.8, "Washington, USA"),
  mk("Pyramid Hefeweizen", "Pyramid Breweries", "Hefeweizen", 5.2, "Washington, USA"),
  mk("Mac & Jack's African Amber", "Mac & Jack's Brewing", "Amber Ale", 5.7, "Washington, USA"),
  mk("Ninkasi Maiden the Shade", "Ninkasi Brewing", "Session IPA", 5.3, "Oregon, USA"),
  mk("10 Barrel Apocalypse IPA", "10 Barrel Brewing", "IPA", 6.8, "Oregon, USA"),

  // ── International expansion ─────────────────────────────────
  mk("Tsingtao Pure Draft", "Tsingtao Brewery", "Helles Lager", 4.3, "China"),
  mk("Yanjing", "Yanjing Brewery", "Asian Lager", 4.0, "China"),
  mk("Snow Beer", "China Resources Snow", "Asian Lager", 4.0, "China"),
  mk("Cass Fresh", "Oriental Brewery", "Asian Lager", 4.5, "South Korea"),
  mk("Max Hite", "Hite Brewery", "Asian Lager", 4.5, "South Korea"),
  mk("Orion", "Orion Breweries", "Asian Lager", 5.0, "Japan"),
  mk("Suntory The Premium Malt's", "Suntory", "Helles Lager", 5.5, "Japan"),
  mk("Coedo Beniaka", "Coedo Brewery", "Imperial Sweet Potato Amber", 7.0, "Japan"),
  mk("Hitachino Nest Espresso Stout", "Hitachino Nest", "Imperial Stout", 7.0, "Japan"),
  mk("Hitachino Nest Real Ginger Ale", "Hitachino Nest", "Spice/Herb Ale", 8.0, "Japan"),
  mk("Y. Market Brewing Pacific Ocean", "Y. Market Brewing", "IPA", 6.5, "Japan"),
  mk("Baird Suruga Bay Imperial IPA", "Baird Brewing", "Double IPA", 8.5, "Japan"),
  mk("Bia Hanoi", "Habeco", "Asian Lager", 4.6, "Vietnam"),
  mk("Tsingtao Stout", "Tsingtao Brewery", "Sweet Stout", 7.5, "China"),
  mk("San Miguel Pale Pilsen", "San Miguel Brewery", "Pilsner", 5.0, "Philippines"),
  mk("Red Horse", "San Miguel Brewery", "Strong Lager", 6.9, "Philippines"),
  mk("Bintang", "PT Multi Bintang Indonesia", "Asian Lager", 4.7, "Indonesia"),
  mk("Beerlao", "Lao Brewery", "Asian Lager", 5.0, "Laos"),
  mk("Angkor", "Cambodia Brewery", "Asian Lager", 5.0, "Cambodia"),
  mk("Lion Lager", "Lion Brewery", "Asian Lager", 4.8, "Sri Lanka"),
  mk("Kingfisher Premium", "United Breweries", "Asian Lager", 4.8, "India"),
  mk("Bira 91 Blonde", "Bira 91", "Belgian Blonde", 4.9, "India"),
  mk("Castle Lager", "South African Breweries", "Pale Lager", 5.0, "South Africa"),
  mk("Windhoek Lager", "Namibia Breweries", "European Lager", 4.0, "Namibia"),
  mk("Tusker Lager", "East African Breweries", "Pale Lager", 4.2, "Kenya"),
  mk("Star Lager", "Nigerian Breweries", "Pale Lager", 5.1, "Nigeria"),
  mk("Bavaria Premium", "Bavaria Brewery", "Pale Lager", 5.0, "Netherlands"),
  mk("Grolsch Premium Lager", "Grolsche Bierbrouwerij", "European Lager", 5.0, "Netherlands"),
  mk("Jever Pilsener", "Friesisches Brauhaus zu Jever", "German Pilsner", 4.9, "Germany"),
  mk("Tucher Helles Hefe Weizen", "Tucher Bräu", "Hefeweizen", 5.2, "Germany"),
  mk("Rothaus Pils", "Rothaus", "German Pilsner", 5.1, "Germany"),
  mk("Köstritzer Schwarzbier", "Köstritzer", "Schwarzbier", 4.8, "Germany"),
  mk("Krombacher Pils", "Krombacher", "German Pilsner", 4.8, "Germany"),
  mk("Erdinger Weissbier", "Erdinger Weißbräu", "Hefeweizen", 5.3, "Germany"),
  mk("Andechser Doppelbock Dunkel", "Andechs", "Doppelbock", 7.1, "Germany"),
  mk("Aecht Schlenkerla Rauchbier Märzen", "Brauerei Heller-Trum", "Rauchbier", 5.1, "Germany"),
  mk("Schneider Aventinus Eisbock", "Schneider Weisse", "Eisbock", 12.0, "Germany"),
  mk("Gaffel Kölsch", "Gaffel", "Kölsch", 4.8, "Germany"),
  mk("Früh Kölsch", "Cölner Hofbräu Früh", "Kölsch", 4.8, "Germany"),
  mk("Uerige Alt", "Uerige Obergärige Hausbrauerei", "Altbier", 4.7, "Germany"),
  mk("Diebels Alt", "Diebels", "Altbier", 4.9, "Germany"),
  mk("De Koninck Bolleke", "Brouwerij De Koninck", "Belgian Pale Ale", 5.2, "Belgium"),
  mk("Leffe Blonde", "Abbaye Notre-Dame de Leffe", "Belgian Blonde Ale", 6.6, "Belgium"),
  mk("Leffe Brune", "Abbaye Notre-Dame de Leffe", "Belgian Dubbel", 6.5, "Belgium"),
  mk("Maredsous 10", "Maredsous Abbey", "Belgian Tripel", 10.0, "Belgium"),
  mk("La Chouffe", "Brasserie d'Achouffe", "Belgian Strong Pale Ale", 8.0, "Belgium"),
  mk("Houblon Chouffe Dobbelen IPA Tripel", "Brasserie d'Achouffe", "Belgian IPA", 9.0, "Belgium"),
  mk("Mc Chouffe", "Brasserie d'Achouffe", "Belgian Strong Dark Ale", 8.0, "Belgium"),
  mk("Affligem Blonde", "Brouwerij De Smedt", "Belgian Blonde", 6.7, "Belgium"),
  mk("St. Bernardus Abt 12", "Brouwerij St. Bernardus", "Belgian Quadrupel", 10.0, "Belgium"),
  mk("St. Bernardus Tripel", "Brouwerij St. Bernardus", "Belgian Tripel", 8.0, "Belgium"),
  mk("Achel 8 Blonde", "Achelse Kluis", "Belgian Tripel", 8.0, "Belgium"),
  mk("Boon Oude Geuze", "Brouwerij Boon", "Lambic", 7.0, "Belgium"),
  mk("Oud Beersel Oude Geuze", "Oud Beersel", "Lambic", 6.0, "Belgium"),
  mk("Drie Fonteinen Oude Geuze", "3 Fonteinen", "Lambic", 6.0, "Belgium"),
  mk("Petrus Aged Pale", "Brouwerij Bavik", "Sour Ale", 7.3, "Belgium"),
  mk("Liefmans Goudenband", "Liefmans Brewery", "Flanders Oud Bruin", 8.0, "Belgium"),
  mk("Rodenbach Grand Cru", "Brouwerij Rodenbach", "Flanders Red Ale", 6.0, "Belgium"),
  mk("Bush Amber", "Brasserie Dubuisson", "Belgian Strong Pale Ale", 12.0, "Belgium"),
  mk("Gulden Draak", "Brouwerij Van Steenberge", "Belgian Strong Dark Ale", 10.5, "Belgium"),
  mk("Tripel Karmeliet", "Brouwerij Bosteels", "Belgian Tripel", 8.4, "Belgium"),
  mk("Birra Moretti", "Birra Moretti", "European Lager", 4.6, "Italy"),
  mk("Peroni Nastro Azzurro", "Peroni", "European Lager", 5.1, "Italy"),
  mk("Menabrea Bionda", "Birra Menabrea", "European Lager", 4.8, "Italy"),
  mk("Birrificio del Ducato Verdi Imperial Stout", "Birrificio del Ducato", "Imperial Stout", 8.2, "Italy"),
  mk("LoverBeer BeerBera", "LoverBeer", "Wild Ale", 8.0, "Italy"),
  mk("Birra Toccalmatto Skizoid", "Birra Toccalmatto", "IPA", 6.0, "Italy"),
  mk("Birrificio Lambrate Montestella", "Lambrate", "Kölsch", 4.9, "Italy"),
  mk("Birra Forst Premium", "Birra Forst", "Helles Lager", 4.8, "Italy"),
  mk("Damm Lemon", "Estrella Damm", "Shandy", 3.2, "Spain"),
  mk("Voll-Damm", "Estrella Damm", "Doppelbock", 7.2, "Spain"),
  mk("Cruzcampo", "Heineken España", "European Lager", 4.8, "Spain"),
  mk("Ambar Especial", "Cervezas Ambar", "European Lager", 5.2, "Spain"),
  mk("Madri Excepcional", "Madri Excepcional", "European Lager", 4.6, "Spain"),
  mk("Innis & Gunn Original", "Innis & Gunn", "Scotch Ale", 6.6, "Scotland, UK"),
  mk("Tennent's Lager", "Tennent Caledonian Breweries", "European Lager", 4.0, "Scotland, UK"),
  mk("Belhaven Wee Heavy", "Belhaven Brewery", "Scotch Ale", 7.4, "Scotland, UK"),
  mk("Caledonian Deuchars IPA", "Caledonian Brewery", "English IPA", 4.4, "Scotland, UK"),
  mk("BrewDog Hazy Jane", "BrewDog", "Hazy IPA", 7.2, "Scotland, UK"),
  mk("BrewDog Dead Pony Club", "BrewDog", "Pale Ale", 3.8, "Scotland, UK"),
  mk("BrewDog Lost Lager", "BrewDog", "Pilsner", 4.5, "Scotland, UK"),
  mk("Cloudwater DDH Pale", "Cloudwater Brew Co.", "American Pale Ale", 5.5, "England, UK"),
  mk("Cloudwater Double IPA", "Cloudwater Brew Co.", "Double IPA", 9.0, "England, UK"),
  mk("Thornbridge Jaipur IPA", "Thornbridge Brewery", "IPA", 5.9, "England, UK"),
  mk("Thornbridge Lukas", "Thornbridge Brewery", "Helles Lager", 4.2, "England, UK"),
  mk("Beavertown Neck Oil", "Beavertown Brewery", "IPA", 4.3, "England, UK"),
  mk("Beavertown Gamma Ray", "Beavertown Brewery", "American Pale Ale", 5.4, "England, UK"),
  mk("Camden Hells Lager", "Camden Town Brewery", "Helles Lager", 4.6, "England, UK"),
  mk("Adnams Ghost Ship", "Adnams Brewery", "English Pale Ale", 4.5, "England, UK"),
  mk("Greene King IPA", "Greene King", "English Bitter", 3.6, "England, UK"),
  mk("Wadworth 6X", "Wadworth Brewery", "English Bitter", 4.1, "England, UK"),
  mk("Marston's Pedigree", "Marston's", "English Pale Ale", 4.5, "England, UK"),
  mk("Hobgoblin", "Wychwood Brewery", "Brown Ale", 4.5, "England, UK"),
  mk("Theakston Old Peculier", "Theakston Brewery", "Old Ale", 5.7, "England, UK"),
  mk("Boddingtons", "Boddingtons Brewery", "English Pale Ale", 3.5, "England, UK"),

  // ── Australia / NZ ──────────────────────────────────────────
  mk("Coopers Pale Ale", "Coopers Brewery", "Australian Pale Ale", 4.5, "Australia"),
  mk("Coopers Best Extra Stout", "Coopers Brewery", "Stout", 6.3, "Australia"),
  mk("XXXX Gold", "Castlemaine Perkins", "Pale Lager", 3.5, "Australia"),
  mk("Tooheys New", "Tooheys", "Pale Lager", 4.6, "Australia"),
  mk("James Boag's Premium", "James Boag's Brewery", "Pale Lager", 5.0, "Australia"),
  mk("Crown Lager", "Carlton & United", "Pale Lager", 4.9, "Australia"),
  mk("Furphy Refreshing Ale", "Little Creatures Brewing", "Pale Ale", 4.4, "Australia"),
  mk("Mountain Goat Steam Ale", "Mountain Goat Beer", "Cream Ale", 4.5, "Australia"),
  mk("Balter XPA", "Balter Brewing", "Pale Ale", 5.0, "Australia"),
  mk("Pirate Life Throwback IPA", "Pirate Life Brewing", "Session IPA", 3.5, "Australia"),
  mk("Young Henrys Newtowner", "Young Henrys", "American Pale Ale", 4.8, "Australia"),
  mk("4 Pines Pacific Ale", "4 Pines Brewing", "American Pale Ale", 3.5, "Australia"),
  mk("Modus Operandi Former Tenant", "Modus Operandi", "Red IPA", 7.8, "Australia"),
  mk("Stomping Ground Gipps St. Pale Ale", "Stomping Ground", "American Pale Ale", 4.6, "Australia"),
  mk("Bridge Road Beechworth Pale Ale", "Bridge Road Brewers", "American Pale Ale", 5.4, "Australia"),
  mk("Mountain Culture Status Quo", "Mountain Culture Beer Co.", "American Pale Ale", 4.4, "Australia"),
  mk("Garage Project Hops on Pointe", "Garage Project", "Pilsner", 5.0, "New Zealand"),
  mk("Garage Project Death From Above", "Garage Project", "IPA", 7.5, "New Zealand"),
  mk("Parrotdog Birdseye", "ParrotDog Brewery", "IPA", 5.8, "New Zealand"),
  mk("Yeastie Boys Gunnamatta", "Yeastie Boys", "Earl Grey IPA", 6.5, "New Zealand"),
  mk("Epic Hop Zombie", "Epic Brewing NZ", "Double IPA", 8.5, "New Zealand"),
  mk("Tuatara APA", "Tuatara Brewing", "American Pale Ale", 5.8, "New Zealand"),
  mk("8 Wired HopWired IPA", "8 Wired Brewing", "IPA", 7.3, "New Zealand"),
  mk("8 Wired iStout", "8 Wired Brewing", "Imperial Stout", 10.0, "New Zealand"),
  mk("Liberty Brewing Yakima Monster", "Liberty Brewing", "American Pale Ale", 5.8, "New Zealand"),
  mk("Behemoth Brewing Chur", "Behemoth Brewing", "American Pale Ale", 5.5, "New Zealand"),
  mk("Mac's Sassy Red", "Mac's Brewery", "Amber Ale", 4.7, "New Zealand"),
  mk("Speight's Gold Medal Ale", "Speight's", "Pale Ale", 4.0, "New Zealand"),

  // ── Latin America expansion ─────────────────────────────────
  mk("Cerveza Patagonia Bohemian Pilsener", "Patagonia Brewing", "Czech Pilsner", 4.9, "Argentina"),
  mk("Quilmes", "Quilmes", "Pilsner", 4.9, "Argentina"),
  mk("Bohemia", "Heineken Mexico", "Vienna Lager", 5.3, "Mexico"),
  mk("Sol", "Heineken Mexico", "Mexican Lager", 4.5, "Mexico"),
  mk("Indio", "Heineken Mexico", "Vienna Lager", 4.1, "Mexico"),
  mk("Cervecería Insurgente La Lupulosa", "Insurgente", "IPA", 7.3, "Mexico"),
  mk("Cervecería Wendlandt Harry Polanco", "Wendlandt", "Red Ale", 5.0, "Mexico"),
  mk("Tempus Doble Malta", "Cervecería Primus", "Vienna Lager", 5.5, "Mexico"),
  mk("Skol", "Ambev", "Pale Lager", 4.7, "Brazil"),
  mk("Bohemia Brazil", "Ambev", "Pale Lager", 5.0, "Brazil"),
  mk("Colorado Indica", "Colorado Brewery", "IPA", 7.0, "Brazil"),
  mk("Cerveja Eisenbahn Weizenbier", "Eisenbahn", "Hefeweizen", 5.0, "Brazil"),
  mk("Wäls Dubbel", "Cervejaria Wäls", "Belgian Dubbel", 7.2, "Brazil"),
  mk("Cristal", "Backus & Johnston", "Pale Lager", 5.0, "Peru"),
  mk("Pilsen Callao", "Backus & Johnston", "Pilsner", 4.9, "Peru"),
  mk("Sierra Andina Don Juan", "Sierra Andina", "IPA", 6.5, "Peru"),
  mk("Imperial", "Florida Ice and Farm Co.", "Pale Lager", 4.6, "Costa Rica"),
  mk("Presidente", "Cervecería Nacional Dominicana", "Pilsner", 5.0, "Dominican Republic"),
  mk("Medalla Light", "Cervecera de Puerto Rico", "Light Lager", 4.2, "Puerto Rico"),
  mk("Red Stripe", "Desnoes & Geddes", "Lager", 4.7, "Jamaica"),
  mk("Carib Lager", "Carib Brewery", "Lager", 5.2, "Trinidad and Tobago"),
  mk("Belikin Premium", "Belize Brewing", "Pale Lager", 4.8, "Belize"),

  // ── Berkshire Brewing Company (from imported dataset) ───────
  mk("Easy Like", "Berkshire Brewing Company", "Hazy IPA", 4.5, "Massachusetts, USA"),
  mk("Inhopnito IPA", "Berkshire Brewing Company", "IPA", 6.2, "Massachusetts, USA"),
  mk("Lost Sailor IPA", "Berkshire Brewing Company", "IPA", 5.8, "Massachusetts, USA"),
  mk("Green Gown Double IPA", "Berkshire Brewing Company", "Double IPA", 8.5, "Massachusetts, USA"),
  mk("Gold Spike Golden Ale", "Berkshire Brewing Company", "Blonde Ale", 4.2, "Massachusetts, USA"),
  mk("River Ale", "Berkshire Brewing Company", "Brown Ale", 5.2, "Massachusetts, USA"),
  mk("Jalapenito IPA", "Berkshire Brewing Company", "IPA", 6.2, "Massachusetts, USA"),
  mk("Black IPA", "Berkshire Brewing Company", "Black IPA", 5.0, "Massachusetts, USA"),
  mk("Tiger Lily Double IPA", "Berkshire Brewing Company", "Double IPA", 8.0, "Massachusetts, USA"),
  mk("Alpha Imperial IPA", "Berkshire Brewing Company", "Double IPA", 8.0, "Massachusetts, USA"),
  mk("BLDG8 The Hazy NEIPA", "Berkshire Brewing Company", "Hazy IPA", 6.5, "Massachusetts, USA"),
  mk("Easy Like Mosaic NEIPA", "Berkshire Brewing Company", "Hazy IPA", 6.8, "Massachusetts, USA"),
  mk("Dandy Lion Haze NEIPA", "Berkshire Brewing Company", "Hazy IPA", 6.8, "Massachusetts, USA"),
  mk("Easy Like Citra NEIPA", "Berkshire Brewing Company", "Hazy IPA", 6.7, "Massachusetts, USA"),
  mk("Weave Got Hops NEIPA", "Berkshire Brewing Company", "Hazy IPA", 7.5, "Massachusetts, USA"),
  mk("Berkshire Session IPA", "Berkshire Brewing Company", "Session IPA", 4.0, "Massachusetts, USA"),
  mk("Turkey Trotter Rotator Brown Ale", "Berkshire Brewing Company", "Brown Ale", 7.5, "Massachusetts, USA"),
  mk("Shea Theater's Rebellion", "Berkshire Brewing Company", "IPA", 6.2, "Massachusetts, USA"),

  // ── Hazy IPA wave (big chunk because every craft brewery makes one) ──
  mk("Vermilion", "Other Half Brewing", "Hazy IPA", 7.0, "New York, USA"),
  mk("Hop Showers", "Other Half Brewing", "IPA", 7.0, "New York, USA"),
  mk("Citra + Mosaic Daydream", "Other Half Brewing", "IPA", 7.0, "New York, USA"),
  mk("Triple Citra Daydream", "Other Half Brewing", "Triple IPA", 11.5, "New York, USA"),
  mk("Foudre Beer", "Other Half Brewing", "Wild Ale", 5.5, "New York, USA"),
  mk("Hill Farmstead Abner", "Hill Farmstead Brewery", "Double IPA", 8.2, "Vermont, USA"),
  mk("Hill Farmstead Ephraim", "Hill Farmstead Brewery", "Double IPA", 10.2, "Vermont, USA"),
  mk("Hill Farmstead Society & Solitude #5", "Hill Farmstead Brewery", "Double IPA", 8.5, "Vermont, USA"),
  mk("Lawson's Triple Sunshine", "Lawson's Finest Liquids", "Triple IPA", 10.5, "Vermont, USA"),
  mk("Lawson's Double Sunshine", "Lawson's Finest Liquids", "Double IPA", 8.0, "Vermont, USA"),
  mk("The Veil Master Shredder", "The Veil Brewing Co.", "Double IPA", 8.5, "Virginia, USA"),
  mk("The Veil Hornswoggler", "The Veil Brewing Co.", "Imperial Stout", 12.0, "Virginia, USA"),
  mk("Equilibrium Photon", "Equilibrium Brewery", "Double IPA", 8.0, "New York, USA"),
  mk("Equilibrium Mc Fluffin'", "Equilibrium Brewery", "Double IPA", 8.0, "New York, USA"),
  mk("Aslin Master of Karate", "Aslin Beer Company", "Double IPA", 8.0, "Virginia, USA"),
  mk("Aslin Orange Starfish", "Aslin Beer Company", "Hazy IPA", 6.7, "Virginia, USA"),
  mk("Foam Hi-Res", "Foam Brewers", "Double IPA", 8.0, "Vermont, USA"),
  mk("Foam Built to Spill", "Foam Brewers", "Hazy IPA", 6.5, "Vermont, USA"),
  mk("Fidens Sunshine Now Pale Ale", "Fidens Brewing", "American Pale Ale", 5.5, "New York, USA"),
  mk("Burlington Maple Breakfast", "Burlington Beer Company", "Imperial Stout", 10.0, "Vermont, USA"),
  mk("Stoneface IPA", "Stoneface Brewing", "IPA", 7.2, "New Hampshire, USA"),
  mk("Backacre Sour Golden Ale", "Backacre", "Wild Ale", 6.5, "Vermont, USA"),
  mk("Sloop Juice Bomb", "Sloop Brewing", "Hazy IPA", 6.5, "New York, USA"),
  mk("Industrial Arts Wrench", "Industrial Arts Brewing", "Hazy IPA", 6.8, "New York, USA"),
  mk("Sand City Plead the Fifth", "Sand City Brewing", "Double IPA", 8.5, "New York, USA"),

  // ── Sours/wild/funk explosion ───────────────────────────────
  mk("Allagash Coolship Resurgam", "Allagash Brewing", "Lambic", 6.0, "Maine, USA"),
  mk("Allagash Confluence Ale", "Allagash Brewing", "Wild Ale", 7.4, "Maine, USA"),
  mk("Crooked Stave Vieille", "Crooked Stave", "Wild Ale", 5.5, "Colorado, USA"),
  mk("Crooked Stave Petite Sour", "Crooked Stave", "Wild Ale", 4.5, "Colorado, USA"),
  mk("Jolly Pumpkin La Roja", "Jolly Pumpkin Artisan Ales", "Wild Ale", 7.2, "Michigan, USA"),
  mk("Jolly Pumpkin Bam Bière", "Jolly Pumpkin Artisan Ales", "Saison", 4.5, "Michigan, USA"),
  mk("Jester King Le Petit Prince", "Jester King Brewery", "Farmhouse Ale", 2.9, "Texas, USA"),
  mk("Jester King Spon", "Jester King Brewery", "Lambic", 6.0, "Texas, USA"),
  mk("Side Project Saison du Fermier", "Side Project Brewing", "Saison", 6.5, "Missouri, USA"),
  mk("Side Project Derivation", "Side Project Brewing", "Imperial Stout", 14.0, "Missouri, USA"),
  mk("Cantillon Iris", "Brasserie Cantillon", "Lambic", 5.0, "Belgium"),
  mk("Cantillon Lou Pepe Framboise", "Brasserie Cantillon", "Lambic", 5.0, "Belgium"),
  mk("Brasserie Cantillon Fou' Foune", "Brasserie Cantillon", "Lambic", 5.0, "Belgium"),
  mk("Hanssens Oude Gueuze", "Hanssens Artisanaal", "Lambic", 6.0, "Belgium"),
  mk("Tilquin Oude Gueuze", "Gueuzerie Tilquin", "Lambic", 6.5, "Belgium"),
  mk("Funk Factory Geuzeria Meerts", "Funk Factory Geuzeria", "Lambic", 4.0, "Wisconsin, USA"),
  mk("De Garde The Mermaid", "De Garde Brewing", "Wild Ale", 6.0, "Oregon, USA"),
  mk("De Garde Bu", "De Garde Brewing", "Wild Ale", 6.5, "Oregon, USA"),
  mk("De Garde Hose Strawberry", "De Garde Brewing", "Wild Ale", 7.5, "Oregon, USA"),
  mk("Casey Family Preserves", "Casey Brewing & Blending", "Wild Ale", 7.0, "Colorado, USA"),
  mk("Casey East Bank", "Casey Brewing & Blending", "Wild Ale", 6.5, "Colorado, USA"),
  mk("Sante Adairius Saison Bernice", "Sante Adairius Rustic Ales", "Saison", 6.7, "California, USA"),
  mk("Sante Adairius West Ashley", "Sante Adairius Rustic Ales", "Wild Ale", 7.2, "California, USA"),

  // ── Stouts (every level) ────────────────────────────────────
  mk("Hair of the Dog Adam", "Hair of the Dog Brewing", "Old Ale", 10.0, "Oregon, USA"),
  mk("Hair of the Dog Fred", "Hair of the Dog Brewing", "American Strong Ale", 10.0, "Oregon, USA"),
  mk("De Molen Hel & Verdoemenis", "Brouwerij De Molen", "Imperial Stout", 10.2, "Netherlands"),
  mk("De Molen Bommen & Granaten", "Brouwerij De Molen", "Barleywine", 15.2, "Netherlands"),
  mk("Närke Kaggen Stormaktsporter", "Närke Kulturbryggeri", "Imperial Stout", 9.5, "Sweden"),
  mk("Omnipollo Yellow Belly", "Omnipollo", "Imperial Stout", 11.0, "Sweden"),
  mk("Omnipollo Selassie", "Omnipollo", "Imperial Stout", 12.0, "Sweden"),
  mk("Mikkeller Black", "Mikkeller", "Imperial Stout", 17.5, "Denmark"),
  mk("BrewDog Black Tokyo Horizon", "BrewDog", "Imperial Stout", 16.5, "Scotland, UK"),
  mk("Põhjala Öö", "Põhjala Brewery", "Imperial Stout", 10.5, "Estonia"),
  mk("Põhjala Pime Öö", "Põhjala Brewery", "Imperial Stout", 13.6, "Estonia"),
  mk("Evil Twin Even More Jesus", "Evil Twin Brewing", "Imperial Stout", 12.0, "New York, USA"),
  mk("Anchorage Brewing A Deal With the Devil", "Anchorage Brewing", "Barleywine", 17.5, "Alaska, USA"),
  mk("Bottle Logic Recursion", "Bottle Logic Brewing", "Imperial Stout", 14.0, "California, USA"),
  mk("Bottle Logic Darkstar November", "Bottle Logic Brewing", "Imperial Stout", 13.5, "California, USA"),
  mk("Funky Buddha Maple Bacon Coffee Porter", "Funky Buddha Brewery", "Porter", 6.4, "Florida, USA"),
  mk("Funky Buddha Last Snow", "Funky Buddha Brewery", "Coffee Porter", 6.4, "Florida, USA"),
  mk("WeldWerks Medianoche", "WeldWerks Brewing", "Imperial Stout", 14.6, "Colorado, USA"),
  mk("Block Fifteen Super Nebula", "Block 15 Brewing", "Imperial Stout", 13.0, "Oregon, USA"),
  mk("AleSmith Vietnamese Speedway", "AleSmith Brewing", "Imperial Stout", 12.5, "California, USA"),
  mk("Hardywood Bourbon Cru", "Hardywood Park Craft Brewery", "Imperial Stout", 9.8, "Virginia, USA"),
  mk("Perennial Abraxas", "Perennial Artisan Ales", "Imperial Stout", 10.0, "Missouri, USA"),
  mk("Perennial Sump Coffee Stout", "Perennial Artisan Ales", "Imperial Stout", 10.5, "Missouri, USA"),
  mk("Prairie Bomb!", "Prairie Artisan Ales", "Imperial Stout", 13.0, "Oklahoma, USA"),
  mk("Prairie Christmas Bomb!", "Prairie Artisan Ales", "Imperial Stout", 13.0, "Oklahoma, USA"),
  mk("3 Floyds BBA Dark Lord", "3 Floyds Brewing", "Imperial Stout", 15.0, "Indiana, USA"),

  // ── Pilsners and lagers, real-deal ──────────────────────────
  mk("Notch Left of the Dial", "Notch Brewing", "American Pale Ale", 4.3, "Massachusetts, USA"),
  mk("Suarez Family Palatine Pils", "Suarez Family Brewery", "German Pilsner", 4.8, "New York, USA"),
  mk("Suarez Family Crispy Little", "Suarez Family Brewery", "Pilsner", 4.5, "New York, USA"),
  mk("Schilling Alexandr", "Schilling Beer Co.", "Czech Pilsner", 5.0, "New Hampshire, USA"),
  mk("Wayfinder Czech-style Pils", "Wayfinder Beer", "Czech Pilsner", 4.8, "Oregon, USA"),
  mk("Wayfinder Hell", "Wayfinder Beer", "Helles Lager", 4.8, "Oregon, USA"),
  mk("Highland Park Timbo Pils", "Highland Park Brewery", "Pilsner", 5.2, "California, USA"),
  mk("Highland Park Refresh-mint", "Highland Park Brewery", "Pilsner", 4.6, "California, USA"),
  mk("Pilsner Urquell Polotmavé", "Pilsner Urquell Brewery", "Czech Amber Lager", 4.5, "Czech Republic"),
  mk("Tegernseer Hell", "Brauerei Tegernsee", "Helles Lager", 4.8, "Germany"),
  mk("Augustiner Edelstoff", "Augustiner-Bräu", "Helles Lager", 5.6, "Germany"),
  mk("Spaten Münchner Helles", "Spaten-Franziskaner-Bräu", "Helles Lager", 5.2, "Germany"),
  mk("Hacker-Pschorr Münchner Hell", "Hacker-Pschorr", "Helles Lager", 5.0, "Germany"),
  mk("Löwenbräu Original", "Löwenbräu", "Helles Lager", 5.2, "Germany"),
  mk("Hofbräu Original", "Hofbräu München", "Helles Lager", 5.1, "Germany"),
  mk("Andechs Spezial Hell", "Andechs", "Helles Lager", 5.9, "Germany"),

  // ── Pumpkin/seasonal/sours/oddballs ─────────────────────────
  mk("Southern Tier Pumking", "Southern Tier Brewing", "Pumpkin Ale", 8.6, "New York, USA"),
  mk("Southern Tier 2X IPA", "Southern Tier Brewing", "Double IPA", 8.2, "New York, USA"),
  mk("Sierra Nevada Hop Bullet", "Sierra Nevada", "Double IPA", 8.0, "California, USA"),
  mk("Sierra Nevada Narwhal", "Sierra Nevada", "Imperial Stout", 10.2, "California, USA"),
  mk("Sierra Nevada Resilience IPA", "Sierra Nevada", "IPA", 6.7, "California, USA"),
  mk("Founders Devil Dancer", "Founders Brewing", "Triple IPA", 12.0, "Michigan, USA"),
  mk("Founders Curmudgeon", "Founders Brewing", "Old Ale", 9.8, "Michigan, USA"),
  mk("Goose Island Bourbon County Coffee Stout", "Goose Island", "Imperial Stout", 14.0, "Illinois, USA"),
  mk("Goose Island Bourbon County Vanilla", "Goose Island", "Imperial Stout", 14.0, "Illinois, USA"),
  mk("Allagash Tripel", "Allagash Brewing", "Belgian Tripel", 9.0, "Maine, USA"),
  mk("Allagash Black", "Allagash Brewing", "Belgian Stout", 7.5, "Maine, USA"),

  // ── Cider crossovers (people log these too) ─────────────────
  mk("Angry Orchard Crisp Apple", "Angry Orchard Cider", "Cider", 5.0, "Ohio, USA"),
  mk("Angry Orchard Rosé", "Angry Orchard Cider", "Cider", 5.5, "Ohio, USA"),
  mk("Strongbow Original", "Strongbow", "Cider", 5.0, "England, UK"),
  mk("Bulmers Original", "Bulmers", "Cider", 4.5, "Ireland"),
  mk("Austin Eastciders Original", "Austin Eastciders", "Cider", 5.0, "Texas, USA"),
  mk("Ace Joker", "Ace Cider", "Cider", 5.0, "California, USA"),

  // ── Hard seltzer crossovers (let's be honest) ───────────────
  mk("White Claw Black Cherry", "White Claw Seltzer", "Hard Seltzer", 5.0, "USA"),
  mk("White Claw Mango", "White Claw Seltzer", "Hard Seltzer", 5.0, "USA"),
  mk("High Noon Pineapple", "High Noon", "Hard Seltzer", 4.5, "USA"),
  mk("Truly Wild Berry", "Truly Hard Seltzer", "Hard Seltzer", 5.0, "USA"),
  mk("Bud Light Seltzer", "Bud Light", "Hard Seltzer", 5.0, "USA"),

  // ── Macro foreign (so friends can log them) ─────────────────
  mk("Beck's Premier Light", "Brauerei Beck & Co.", "Light Lager", 2.3, "Germany"),
  mk("Pacifico Sunbright", "Grupo Modelo", "Mexican Lager", 5.0, "Mexico"),
  mk("Corona Light", "Grupo Modelo", "Light Lager", 4.5, "Mexico"),
  mk("Corona Premier", "Grupo Modelo", "Light Lager", 4.0, "Mexico"),
  mk("Corona Familiar", "Grupo Modelo", "Mexican Lager", 4.8, "Mexico"),
  mk("Heineken Silver", "Heineken", "Light Lager", 4.0, "Netherlands"),
  mk("Tecate Light", "Heineken Mexico", "Light Lager", 4.0, "Mexico"),
  mk("Sapporo Reserve", "Sapporo Brewery", "Japanese Lager", 5.0, "Japan"),
  mk("Asahi Black", "Asahi Breweries", "Schwarzbier", 5.5, "Japan"),
  mk("Kirin Light", "Kirin Brewery", "Light Lager", 3.3, "Japan"),
  mk("Beerlao Dark", "Lao Brewery", "Schwarzbier", 6.5, "Laos"),
  mk("Vinh Saigon", "SABECO", "Asian Lager", 4.9, "Vietnam"),

  // ── More US micro/macro folks log ────────────────────────────
  mk("Michelob Ultra", "Anheuser-Busch", "Light Lager", 4.2, "Missouri, USA"),
  mk("Michelob Amber Bock", "Anheuser-Busch", "Bock", 5.2, "Missouri, USA"),
  mk("Natural Light", "Anheuser-Busch", "Light Lager", 4.2, "Missouri, USA"),
  mk("Busch Light", "Anheuser-Busch", "Light Lager", 4.1, "Missouri, USA"),
  mk("Keystone Light", "Molson Coors", "Light Lager", 4.13, "Colorado, USA"),
  mk("Hamm's Premium", "Molson Coors", "American Lager", 4.7, "USA"),
  mk("Old Milwaukee", "Pabst Brewing Co.", "American Lager", 4.5, "USA"),
  mk("Schlitz", "Pabst Brewing Co.", "American Lager", 4.6, "USA"),
  mk("Olympia Beer", "Pabst Brewing Co.", "American Lager", 4.5, "USA"),
  mk("Rainier Beer", "Pabst Brewing Co.", "American Lager", 4.6, "Washington, USA"),
  mk("Hamm's Special Light", "Pabst Brewing Co.", "Light Lager", 3.9, "USA"),
  mk("Strohs Bohemian Style", "Pabst Brewing Co.", "American Lager", 4.7, "USA"),

  // ── Iconic UK + Irish ───────────────────────────────────────
  mk("Guinness Extra Stout", "Guinness", "Irish Stout", 5.6, "Dublin, Ireland"),
  mk("Guinness Nitro IPA", "Guinness", "IPA", 5.8, "Dublin, Ireland"),
  mk("Guinness Blonde", "Guinness", "American Lager", 5.0, "Dublin, Ireland"),
  mk("Beamish Irish Stout", "Beamish & Crawford", "Irish Stout", 4.1, "Ireland"),
  mk("Kilkenny Cream Ale", "Kilkenny", "Irish Red Ale", 4.3, "Ireland"),
  mk("Harp Lager", "Guinness", "Pale Lager", 5.0, "Ireland"),
  mk("Carling Black Label", "Molson Coors", "Pale Lager", 4.0, "England, UK"),
  mk("John Smith's Extra Smooth", "John Smith's Brewery", "English Bitter", 3.6, "England, UK"),
  mk("Bombardier", "Wells & Young's", "English Bitter", 4.7, "England, UK"),
  mk("Tetley's Smoothflow", "Tetley's", "English Bitter", 3.6, "England, UK"),

  // ── More from China/SE Asia/Africa ──────────────────────────
  mk("Carlsberg Smooth Draught", "Carlsberg", "Pale Lager", 5.0, "Denmark"),
  mk("Carlsberg Elephant", "Carlsberg", "Strong Lager", 7.2, "Denmark"),
  mk("Tuborg Green", "Tuborg", "Pale Lager", 4.6, "Denmark"),
  mk("Mythos", "Mythos Brewery", "European Lager", 4.7, "Greece"),
  mk("Alfa Hellenic Lager", "Athenian Brewery", "European Lager", 5.0, "Greece"),
  mk("Mahou Negra", "Mahou", "Schwarzbier", 5.5, "Madrid, Spain"),
  mk("San Miguel Especial", "Mahou-San Miguel", "Pale Lager", 5.4, "Spain"),
  mk("Madri Excepcional", "Madri Excepcional", "Helles Lager", 4.6, "Spain"),
  mk("Estrella Galicia", "Estrella Galicia", "Pale Lager", 5.5, "Spain"),
  mk("Cusqueña Negra", "Backus & Johnston", "Schwarzbier", 5.6, "Peru"),
  mk("Polar Ice", "Cervecería Polar", "Pale Lager", 5.0, "Venezuela"),
  mk("Polar Light", "Cervecería Polar", "Light Lager", 3.5, "Venezuela"),
  mk("Quilmes Cristal", "Quilmes", "Pale Lager", 4.9, "Argentina"),
  mk("Quilmes Stout", "Quilmes", "Stout", 5.7, "Argentina"),
  mk("Bohemia Oscura", "Heineken Mexico", "Schwarzbier", 5.3, "Mexico"),
  mk("Carta Blanca", "Heineken Mexico", "Mexican Lager", 4.5, "Mexico"),
  mk("Superior", "Heineken Mexico", "Mexican Lager", 4.5, "Mexico"),
  mk("Bavaria Light", "Bavaria Brewery", "Light Lager", 3.5, "Netherlands"),
  mk("Grolsch Premium Pilsner", "Grolsche Bierbrouwerij", "European Lager", 5.0, "Netherlands"),
  mk("Grolsch Radler 2%", "Grolsche Bierbrouwerij", "Shandy", 2.0, "Netherlands"),

  // ── More farmhouse + sours ──────────────────────────────────
  mk("Brasserie Dupont Avec les Bons Vœux", "Brasserie Dupont", "Saison", 9.5, "Belgium"),
  mk("Brasserie Dupont Moinette Blonde", "Brasserie Dupont", "Belgian Strong Pale Ale", 8.5, "Belgium"),
  mk("Brasserie Dupont Foret", "Brasserie Dupont", "Saison", 7.5, "Belgium"),
  mk("Fantôme Saison", "Brasserie Fantôme", "Saison", 8.0, "Belgium"),
  mk("Blaugies Saison d'Epeautre", "Brasserie de Blaugies", "Saison", 6.0, "Belgium"),
  mk("Brasserie de la Senne Taras Boulba", "Brasserie de la Senne", "Belgian Pale Ale", 4.5, "Belgium"),
  mk("Brasserie de la Senne Zinnebir", "Brasserie de la Senne", "Belgian Pale Ale", 6.0, "Belgium"),

  // ── Recent darlings nobody's added yet ──────────────────────
  mk("Trillium Sleeper Street", "Trillium Brewing", "Double IPA", 8.0, "Massachusetts, USA"),
  mk("Trillium Streetlights", "Trillium Brewing", "American Pale Ale", 5.4, "Massachusetts, USA"),
  mk("Tree House Hurricane", "Tree House Brewing", "Hazy IPA", 6.0, "Massachusetts, USA"),
  mk("Tree House Lights Out", "Tree House Brewing", "Imperial Stout", 12.0, "Massachusetts, USA"),
  mk("Tree House Curiosity", "Tree House Brewing", "Double IPA", 8.2, "Massachusetts, USA"),
  mk("Monkish Money Talks", "Monkish Brewing", "Triple IPA", 11.0, "California, USA"),
  mk("Monkish Magic Markers", "Monkish Brewing", "Hazy IPA", 7.0, "California, USA"),
  mk("Toppling Goliath SR-71", "Toppling Goliath", "Imperial Stout", 14.5, "Iowa, USA"),
  mk("Tired Hands HopHands", "Tired Hands Brewing", "American Pale Ale", 5.5, "Pennsylvania, USA"),
  mk("Tired Hands Saison HighwaytoHell", "Tired Hands Brewing", "Saison", 5.0, "Pennsylvania, USA"),
  mk("Hudson Valley Incandenza", "Hudson Valley Brewery", "Sour IPA", 7.4, "New York, USA"),
  mk("Hudson Valley Sigil", "Hudson Valley Brewery", "Sour IPA", 7.0, "New York, USA"),
  mk("450 North Slushy", "450 North Brewing", "Berliner Weisse", 5.5, "Indiana, USA"),
  mk("450 North Smoothie Pina Colada", "450 North Brewing", "Berliner Weisse", 6.0, "Indiana, USA"),

  // ── Stuff for old-school / casual drinkers ──────────────────
  mk("Sam Adams Summer Ale", "Boston Beer Company", "American Pale Wheat Ale", 5.3, "Massachusetts, USA"),
  mk("Sam Adams Octoberfest", "Boston Beer Company", "Märzen", 5.3, "Massachusetts, USA"),
  mk("Sam Adams Cold Snap", "Boston Beer Company", "Witbier", 5.3, "Massachusetts, USA"),
  mk("Sam Adams Cream Stout", "Boston Beer Company", "Milk Stout", 4.9, "Massachusetts, USA"),
  mk("Sam Adams Utopias", "Boston Beer Company", "American Strong Ale", 28.0, "Massachusetts, USA"),
  mk("Blue Moon Belgian White", "Blue Moon Brewing", "Witbier", 5.4, "Colorado, USA"),
  mk("Blue Moon Mango Wheat", "Blue Moon Brewing", "American Pale Wheat Ale", 5.4, "Colorado, USA"),
  mk("Shock Top Belgian White", "Shock Top Brewing", "Witbier", 5.2, "Missouri, USA"),
  mk("Leinenkugel Summer Shandy", "Jacob Leinenkugel Brewing", "Shandy", 4.2, "Wisconsin, USA"),
  mk("Leinenkugel Honey Weiss", "Jacob Leinenkugel Brewing", "Hefeweizen", 4.9, "Wisconsin, USA"),
  mk("Goose 312 Urban Pale Ale", "Goose Island", "American Pale Ale", 5.4, "Illinois, USA"),

  // ── Hard-to-find but cult-favorite ──────────────────────────
  mk("Cigar City Marshal Zhukov's Imperial Stout", "Cigar City Brewing", "Imperial Stout", 11.0, "Florida, USA"),
  mk("Cigar City Tropical Punch", "Cigar City Brewing", "Berliner Weisse", 4.4, "Florida, USA"),
  mk("Bottle Logic Leche Loco", "Bottle Logic Brewing", "Imperial Stout", 14.0, "California, USA"),
  mk("WeldWerks Juicy Bits", "WeldWerks Brewing", "Hazy IPA", 6.7, "Colorado, USA"),
  mk("Half Acre Big Hugs Imperial Stout", "Half Acre Beer Co.", "Imperial Stout", 10.0, "Illinois, USA"),
  mk("Modern Times City of the Sun", "Modern Times Beer", "IPA", 6.8, "California, USA"),
  mk("Modern Times Lomaland", "Modern Times Beer", "Saison", 5.0, "California, USA"),
  mk("Threes Vliet", "Threes Brewing", "Pilsner", 4.8, "New York, USA"),
  mk("Threes Tobacco Bonanza", "Threes Brewing", "Imperial Stout", 8.0, "New York, USA"),
  mk("Civil Society Fresh", "Civil Society Brewing", "Hazy IPA", 6.5, "Florida, USA"),
  mk("J. Wakefield El Jefe Speaks", "J. Wakefield Brewing", "Imperial Stout", 11.0, "Florida, USA"),
];

window.STYLES = STYLES;
window.BEER_SEEDS = BEER_SEEDS;
window.beerIdSlug = slug;
